# Generated by Django 2.1.2 on 2018-10-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20181011_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(help_text='Enter your first name', max_length=45)),
                ('lName', models.CharField(help_text='Enter your last name', max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('school', models.CharField(help_text='Enter school graduated from', max_length=50)),
                ('yearGrad', models.PositiveSmallIntegerField(help_text='Enter graduation year')),
                ('major', models.CharField(help_text='Enter your major', max_length=70)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
    ]
