# Generated by Django 2.1.2 on 2018-11-26 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_auto_20181126_1147'),
        ('attendance', '0009_auto_20181126_1010'),
    ]

    operations = [
    ]
